# Exercise the actual executable from a different cwd, including a Unicode EXE path.
string(RANDOM LENGTH 10 nonce)
set(sandbox "${TEST_ROOT}/runtime-${nonce}")
set(app_dir "${sandbox}/中文目录")
file(MAKE_DIRECTORY "${app_dir}")
file(COPY "${APP}" DESTINATION "${app_dir}")
get_filename_component(app_name "${APP}" NAME)
set(executable "${app_dir}/${app_name}")
set(atlas "${app_dir}/metro.mbtiles")
file(SHA256 "${SOURCE_ATLAS}" expected)
if(NOT BUNDLED)
    execute_process(COMMAND "${executable}" --snapshot missing.json 100 35
                    WORKING_DIRECTORY "${sandbox}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(result EQUAL 0 OR EXISTS "${atlas}")
        message(FATAL_ERROR "Development executable must reject a missing sibling atlas")
    endif()
    file(COPY "${SOURCE_ATLAS}" DESTINATION "${app_dir}")
endif()
execute_process(COMMAND "${executable}" --snapshot frame.json 100 35 tyxl gznz
                WORKING_DIRECTORY "${sandbox}" RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT EXISTS "${sandbox}/frame.json")
    message(FATAL_ERROR "Sibling atlas startup/snapshot failed: ${result}")
endif()
file(SHA256 "${atlas}" actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Extracted/copied atlas differs from build source")
endif()
# Corruption must be reported, never repaired by overwriting user data.
file(WRITE "${atlas}" "existing user atlas")
execute_process(COMMAND "${executable}" --snapshot invalid.json 100 35
                WORKING_DIRECTORY "${sandbox}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
file(READ "${atlas}" preserved)
if(result EQUAL 0 OR NOT preserved STREQUAL "existing user atlas")
    message(FATAL_ERROR "Existing atlas was overwritten or invalid data was accepted")
endif()
file(REMOVE "${atlas}")
file(MAKE_DIRECTORY "${atlas}")
execute_process(COMMAND "${executable}" --snapshot directory.json 100 35
                WORKING_DIRECTORY "${sandbox}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "Directory at atlas path was accepted")
endif()
file(GLOB leftovers "${app_dir}/metro.mbtiles.tmp-*")
if(leftovers)
    message(FATAL_ERROR "Partial extraction files left behind: ${leftovers}")
endif()
