"""Build editable full-network artwork from manually placed centerlines.

Standard-library only. Does not read old edge geometry or write runtime data.
"""

import argparse
import base64
import copy
import hashlib
import json
import math
import xml.etree.ElementTree as ET
from itertools import pairwise
from pathlib import Path

from calibration_routes import COLORS, ROUTES, STATION_SEEDS
from create_svg_trial import INK, ROOT, SOD, SVG, element, layer


def point(value):
    return complex(value[0], value[1])


def xy(value):
    return f"{value.real:.3f},{value.imag:.3f}"


def evaluate(segment, t):
    a, c, b = segment
    return (
        (1 - t) * a + t * b
        if c is None
        else ((1 - t) ** 2 * a + 2 * t * (1 - t) * c + t * t * b)
    )


def centerline(knots):
    """Round a manual corner by a quadratic with bounded tangent cutbacks."""
    result = []
    cursor = point(knots[0])
    for i in range(1, len(knots) - 1):
        a, b, c = (point(knots[j]) for j in (i - 1, i, i + 1))
        radius = knots[i][2] if len(knots[i]) > 2 else 28
        cut = min(radius, abs(b - a) * 0.45, abs(c - b) * 0.45)
        entry = b + (a - b) / abs(a - b) * cut
        leave = b + (c - b) / abs(c - b) * cut
        result.append((cursor, None, entry))
        result.append((entry, b, leave))
        cursor = leave
    result.append((cursor, None, point(knots[-1])))
    return result


def project(segments, seed):
    """Locate a station along an already manually drawn curve, not the bitmap."""
    best = (math.inf, 0.0)
    for i, segment in enumerate(segments):
        # Bound curve approximation to small steps, then project onto chords.
        a, c, b = segment
        length = abs(b - a) if c is None else abs(c - a) + abs(b - c)
        steps = max(1, math.ceil(length / 2))
        previous = a
        for j in range(1, steps + 1):
            current = evaluate(segment, j / steps)
            delta = current - previous
            u = (
                0
                if not abs(delta)
                else max(
                    0,
                    min(
                        1,
                        (
                            (seed - previous).real * delta.real
                            + (seed - previous).imag * delta.imag
                        )
                        / abs(delta) ** 2,
                    ),
                )
            )
            q = previous + u * delta
            candidate = (abs(q - seed), i + (j - 1 + u) / steps)
            best = min(best, candidate)
            previous = current
    return best


def position(segments, offset):
    i = min(int(offset), len(segments) - 1)
    return evaluate(segments[i], offset - i)


def portion(segments, start, end):
    """Split quadratic segments exactly; keep SVG control points editable."""
    commands = ["M " + xy(position(segments, start))]
    for i, segment in enumerate(segments):
        lo, hi = max(0.0, start - i), min(1.0, end - i)
        if hi <= lo:
            continue
        a, c, b = segment
        q0, q1 = evaluate(segment, lo), evaluate(segment, hi)
        if c is None:
            commands.append("L " + xy(q1))
        else:
            derivative_half = (1 - lo) * (c - a) + lo * (b - c)
            control = q0 + (hi - lo) * derivative_half
            commands.append("Q " + xy(control) + " " + xy(q1))
    return " ".join(commands)


def components(edges):
    result = []
    for edge in edges:
        if not result or result[-1][-1]["to_id"] != edge["from_id"]:
            result.append([])
        result[-1].append(edge)
    return result


def make_root(image_bytes):
    root = ET.Element(
        f"{{{SVG}}}svg",
        {
            "width": "4096",
            "height": "4096",
            "viewBox": "0 0 4096 4096",
            "version": "1.1",
        },
    )
    element(root, "title").text = "广州及佛山线网：4096×4096 人工描线校准稿"
    element(root, "desc").text = (
        "原图目视初校；各线路独立可编辑，保留断开区间。"
        "不是运行时瓦片；原图以外的线路不在本稿范围内。"
    )
    background = layer(root, "reference", "00 原图（锁定，可隐藏）")
    background.set(f"{{{SOD}}}insensitive", "true")
    image = element(background, "image", x="0", y="0", width="4096", height="4096")
    image.set(
        "{http://www.w3.org/1999/xlink}href",
        "data:image/png;base64," + base64.b64encode(image_bytes).decode("ascii"),
    )
    return root


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=ROOT / "data/calibration/network.svg"
    )
    parser.add_argument(
        "--replace-generated",
        action="store_true",
        help="Replace only an unchanged output previously generated by this tool",
    )
    args = parser.parse_args()
    output = args.output.resolve()
    report_path = output.with_suffix(".report.json")
    if output.exists():
        if not args.replace_generated or not report_path.exists():
            raise SystemExit("Output exists; refusing to overwrite artwork")
        old = json.loads(report_path.read_text("utf-8"))
        if hashlib.sha256(output.read_bytes()).hexdigest() != old.get("svg_sha256"):
            raise SystemExit(
                "SVG has been edited; refusing to overwrite manual changes"
            )
    network = json.loads((ROOT / "data/source/network.json").read_text("utf-8"))
    stations = {s["id"]: s for s in network["stations"]}
    seeds = {
        int(s): complex(float(x), float(y))
        for s, x, y in (row.split() for row in STATION_SEEDS.strip().splitlines())
    }
    assert set(seeds) == set(stations), "Every station needs an explicit visual seed"
    image_bytes = (ROOT / "data/railway.png").read_bytes()
    root = make_root(image_bytes)
    marks = layer(root, "station-anchors", "90 线路站点锚点（可隐藏）")
    labels = layer(root, "station-labels", "91 独立站名（默认隐藏）", True)
    labels.set(
        "style",
        "display:none;fill:#111;font-family:Microsoft YaHei,sans-serif;font-size:15px",
    )
    report = {
        "status": "visually traced draft; SVG only",
        "source_sha256": hashlib.sha256(image_bytes).hexdigest(),
        "lines": [],
    }
    all_edge_ids = set()
    for line in network["lines"]:
        lid = line["id"]
        group = layer(root, f"line-{lid}", f"{lid:02} {line['name']}")
        # Put geometry under the station/label layers in document paint order.
        root.remove(group)
        root.insert(list(root).index(marks), group)
        group.set(
            "style",
            f"fill:none;stroke:#{COLORS[lid]};stroke-width:3;"
            "stroke-linecap:round;stroke-linejoin:round",
        )
        mark_group = layer(marks, f"anchors-line-{lid}", line["name"])
        mark_group.set("style", f"fill:white;stroke:#{COLORS[lid]};stroke-width:1.5")
        edges = [e for e in network["edges"] if e["line_id"] == lid]
        offsets = []
        line_anchors = {}
        if lid == 3:
            original = ET.parse(ROOT / "data/calibration/line2-full.svg").getroot()
            ns = {"s": SVG}
            if original.attrib.get("viewBox") != "0 0 4096 4096":
                raise ValueError(
                    "Line 2 artwork must use the original 4096px coordinate system"
                )
            for key in ("line-3", "anchors"):
                source_group = original.find(f"s:g[@id='{key}']", ns)
                if source_group is None or any(
                    "transform" in e.attrib for e in source_group.iter()
                ):
                    raise ValueError(
                        "Flatten Line 2 layer/object transforms before assembling"
                    )
            paths = original.findall("s:g[@id='line-3']/s:path", ns)
            assert {int(p.attrib["id"][5:]) for p in paths} == {e["id"] for e in edges}
            for p in paths:
                group.append(copy.deepcopy(p))
            for c in original.findall("s:g[@id='anchors']/s:circle", ns):
                line_anchors[int(c.attrib["data-station-id"])] = complex(
                    float(c.attrib["cx"]), float(c.attrib["cy"])
                )
        else:
            runs = components(edges)
            assert len(runs) == len(ROUTES[lid]), f"Component mismatch: {lid}"
            for run, knots in zip(runs, ROUTES[lid]):
                segments = centerline(knots)
                ids = [run[0]["from_id"]] + [e["to_id"] for e in run]
                locations = [project(segments, seeds[s])[1] for s in ids]
                # The ring visits its starting station again at its final end.
                locations[0], locations[-1] = 0.0, float(len(segments))
                assert all(a < b for a, b in pairwise(locations)), (
                    f"Non-monotonic stations on {line['name']}: {list(zip(ids, locations))}"
                )
                for sid, t in zip(ids, locations):
                    anchor = position(segments, t)
                    if sid in line_anchors:
                        assert abs(line_anchors[sid] - anchor) < 0.01, (
                            f"Inconsistent shared anchor: line {lid}, station {sid}"
                        )
                    line_anchors[sid] = anchor
                    offsets.append(
                        {
                            "station_id": sid,
                            "seed_offset_px": round(abs(anchor - seeds[sid]), 2),
                        }
                    )
                for edge, a, b in zip(run, locations, locations[1:]):
                    p = element(
                        group,
                        "path",
                        id=f"edge-{edge['id']}",
                        d=portion(segments, a, b),
                    )
                    p.set("data-line-id", str(lid))
                    p.set("data-from-id", str(edge["from_id"]))
                    p.set("data-to-id", str(edge["to_id"]))
                    p.set(
                        f"{{{INK}}}label",
                        stations[edge["from_id"]]["name"]
                        + "—"
                        + stations[edge["to_id"]]["name"],
                    )
        for sid, anchor in line_anchors.items():
            c = element(
                mark_group,
                "circle",
                id=f"station-{sid}-line-{lid}",
                cx=f"{anchor.real:.3f}",
                cy=f"{anchor.imag:.3f}",
                r="4",
            )
            c.set("data-station-id", str(sid))
            c.set("data-line-id", str(lid))
            c.set(f"{{{INK}}}label", stations[sid]["name"])
        report["lines"].append(
            {
                "line_id": lid,
                "name": line["name"],
                "svg_color": COLORS[lid],
                "edges": len(edges),
                "stations": len(line_anchors),
                "seed_projection": offsets,
            }
        )
        all_edge_ids.update(e["id"] for e in edges)
    # A single independently editable label per logical station.
    for sid, seed in seeds.items():
        t = element(
            labels,
            "text",
            id=f"label-{sid}",
            x=f"{seed.real + 18:.3f}",
            y=f"{seed.imag - 12:.3f}",
        )
        t.set("data-station-id", str(sid))
        t.text = stations[sid]["name"]
    assert all_edge_ids == {e["id"] for e in network["edges"]}
    ids = [e.attrib["id"] for e in root.iter() if "id" in e.attrib]
    assert len(ids) == len(set(ids))
    report["station_count"] = len(stations)
    report["edge_count"] = len(all_edge_ids)
    report["line_count"] = len(network["lines"])
    report["skipped_edges"] = network.get("skipped_edges", [])
    output.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(root)
    payload = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    report["svg_sha256"] = hashlib.sha256(payload).hexdigest()
    output.write_bytes(payload)
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", "utf-8"
    )
    print(
        f"{output}: {len(network['lines'])} lines, {len(stations)} stations, {len(all_edge_ids)} edges"
    )


if __name__ == "__main__":
    main()
