# Build the vendored C core/WinCon backend, not upstream demos or other ports.
set(pdc_source "${PROJECT_SOURCE_DIR}/lib/pdcursesmod")
if(NOT EXISTS "${pdc_source}/curses.h" OR NOT EXISTS "${pdc_source}/pdcurses/addch.c")
    message(FATAL_ERROR "Missing vendored PDCursesMod sources in lib/pdcursesmod")
endif()
file(GLOB pdc_core CONFIGURE_DEPENDS "${pdc_source}/pdcurses/*.c")
set(pdc_wincon)
foreach(module pdcclip pdcdisp pdcgetsc pdckbd pdcscrn pdcsetsc pdcutil)
    list(APPEND pdc_wincon "${pdc_source}/wincon/${module}.c")
endforeach()
add_library(gzmp_pdcurses STATIC ${pdc_core} ${pdc_wincon})
set_property(TARGET gzmp_pdcurses PROPERTY C_STANDARD 17)
target_compile_definitions(gzmp_pdcurses PUBLIC PDC_WIDE PDC_FORCE_UTF8)
target_include_directories(gzmp_pdcurses SYSTEM PUBLIC "${pdc_source}")
target_link_libraries(gzmp_pdcurses PUBLIC winmm)
